#!/usr/bin/bash

set -e
if [ $# -le 0 ]; then
    echo "Usage: generate_isr.sh <isr_gen.c>"
    exit 1
fi

ISR_GEN_C=$1

#
# Generate C file
#
echo "// !!! THIS FILE IS AUTOGENERATED !!!" >> $ISR_GEN_C

echo "" >> $ISR_GEN_C
echo "#include <kernel/util/assembly.h>" >> $ISR_GEN_C
echo "#include <kernel/arch/i686/idt.h>" >> $ISR_GEN_C
echo "#include <kernel/arch/i686/gdt.h>" >> $ISR_GEN_C

echo "" >> $ISR_GEN_C
echo "// Defined in ASM" >> $ISR_GEN_C
for i in $(seq 0 255); do
    echo "void ASMCALL ISR_${i}();" >> $ISR_GEN_C
done

echo "" >> $ISR_GEN_C
echo "void ISR_InitializeGates()" >> $ISR_GEN_C
echo "{" >> $ISR_GEN_C

for i in $(seq 0 255); do
    echo "    IDT_SetGate(${i}, ISR_${i}, GDT_CODE_SEGMENT, (IDT_FLAG_RING0 | IDT_FLAG_GATE_32BIT_INT));" >> $ISR_GEN_C
done

echo "}" >> $ISR_GEN_C
echo "" >> $ISR_GEN_C
