#!/usr/bin/bash

set -e
if [ $# -le 0 ]; then
    echo "Usage: generate_isr.sh <isr_gen.inc>"
    exit 1
fi

ISR_GEN_ASM=$1
ISR_WITH_ERROR_CODE="8 10 11 12 13 14 17 21 29 30"

#
# Generate ASM file
#

echo "; !!! THIS FILE IS AUTOGENERATED !!!" >> $ISR_GEN_ASM
echo "" >> $ISR_GEN_ASM

echo "; Definitions" >> $ISR_GEN_ASM
for i in $(seq 0 255); do
    if echo "$ISR_WITH_ERROR_CODE" | grep -q "\b${i}\b"; then
        echo "ISR_ERRORCODE ${i}" >> $ISR_GEN_ASM
    else
        echo "ISR_NOERRORCODE ${i}" >> $ISR_GEN_ASM
    fi
done

echo "" >> $ISR_GEN_ASM